main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('wizards/', views.wizards_index, name='index'),
    path('wizards/<int:wizard_id>/', views.wizards_detail, name='detail'),
    path('wizards/create', views.WizardCreate.as_view(), name='wizards_create'),
    path('wizards/<int:pk>/update', views.WizardUpdate.as_view(), name='wizards_update'),
    path('wizards/<int:pk>/delete', views.WizardDelete.as_view(), name='wizards_delete'),
    path('wizards/<int:wizard_id>/add_wand/', views.add_wand, name='add_wand'),
    path('wizards/<int:wizard_id>/assoc_spell/<int:spell_id>/', views.assoc_spell, name='assoc_spell'),
    path('wizards/<int:wizard_id>/assoc_spell/<int:spell_id>/delete/', views.assoc_spell_delete, name='assoc_spell_delete'),
    path('spells/', views.SpellList.as_view(), name='spells_index'),
    path('spells/<int:pk>/', views.SpellDetail.as_view(), name='spells_detail'),
    path('spells/create/', views.SpellCreate.as_view(), name='spells_create'),
    path('spells/<int:pk>/update/', views.SpellUpdate.as_view(), name='spells_update'),
    path('spells/<int:pk>/delete/', views.SpellDelete.as_view(), name='spells_delete'),
    path('wizards/<int:wizard_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

wandcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Spell(models.Model):
    name = models.CharField(max_length=100)
    action = models.TextField(max_length=500)
    

    def __str__(self):
        return f"{self.name} {self.action}"
    
    def get_absolute_url(self):
        return reverse('spells_detail', kwargs={'pk': self.id})


class Wizard(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    house = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)
    spells = models.ManyToManyField(Spell)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'wizard_id': self.id})


class Wand(models.Model):
    length = models.CharField(max_length=100)
    core = models.CharField(max_length=100)
    wood = models.CharField(max_length=100)
  
    wizard = models.ForeignKey(Wizard, on_delete=models.CASCADE)
    def __str__(self):
        return f"Wand Description: {self.length} {self.core} {self.wood}"

class Photo(models.Model):
    url = models.CharField(max_length=200)
    wizard = models.ForeignKey(Wizard, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for wizard_id: {self.wizard_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Wand

class WandForm(ModelForm):
    class Meta:
        model = Wand
        fields = ['length', 'core', 'wood']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Wizard, Spell, Photo
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import WandForm

import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'wand-collector'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def wizards_index(request):
    wizards = Wizard.objects.filter(user=request.user)
    return render(request, 'wizards/index.html', { 'wizards': wizards })

@login_required
def wizards_detail(request, wizard_id):
    wizard = Wizard.objects.get(id=wizard_id)
    wand_form = WandForm()
    spells_wizard_doesnt_have = Spell.objects.exclude(id__in = wizard.spells.all().values_list('id'))
    return render(request, 'wizards/detail.html', {'wizard' : wizard, 'wand_form': wand_form, 'spells': spells_wizard_doesnt_have })

@login_required
def add_wand(request, wizard_id):
    form = WandForm(request.POST)
    if form.is_valid():
        new_wand = form.save(commit=False)
        new_wand.wizard_id = wizard_id 
        new_wand.save() 
    return redirect('detail', wizard_id=wizard_id)



@login_required
def assoc_spell(request, wizard_id, spell_id):
    Wizard.objects.get(id=wizard_id).spells.add(spell_id)
    return redirect('detail', wizard_id=wizard_id)

@login_required
def assoc_spell_delete(request, wizard_id, spell_id):
    Wizard.objects.get(id=wizard_id).spells.remove(spell_id)
    return redirect('detail', wizard_id=wizard_id)

@login_required
def add_photo(request, wizard_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, wizard_id=wizard_id)
            photo.save()
        except Exception as error:
            print('Error uploading photo:', error)
            return redirect('detail', wizard_id=wizard_id)
    return redirect('detail', wizard_id=wizard_id)
    
def signup(request):
    error_message = ''
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = "Invalid Info - Please Try Again"
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class WizardCreate(LoginRequiredMixin, CreateView):
    model = Wizard
    fields = ['name', 'age', 'house', 'profession']
    success_url = '/wizards/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class WizardUpdate(LoginRequiredMixin, UpdateView):
    model = Wizard
    fields = ['age', 'house', 'profession']

class WizardDelete(LoginRequiredMixin, DeleteView):
    model = Wizard
    success_url = '/wizards/'

class SpellList(LoginRequiredMixin, ListView):
    model = Spell
    template_name = 'spells/index.html'

class SpellDetail(LoginRequiredMixin, DetailView):
    model = Spell
    template_name = 'spells/detail.html'

class SpellCreate(LoginRequiredMixin, CreateView):
    model = Spell
    fields = ['name', 'action']

class SpellUpdate(LoginRequiredMixin, UpdateView):
    model = Spell
    fields = ['name', 'action']

class SpellDelete(LoginRequiredMixin, DeleteView):
    model = Spell
    success_url = '/spells/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

    <h1>Wizard About</h1>
    
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Wizard Registry</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="leftbrang-logo">&nbsp;&nbsp;Wizard Registry</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'wizards_create' %}">Add Wizard</a></li>
            <li><a href="{% url 'index' %}">View All Wizards</a></li>
            <li><a href="{% url 'spells_index' %}"> View All Spells </a></li>
            <li><a href="{% url 'spells_create' %}"> Add a Spell </a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved &copy; 2022 Wizard Registry &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Register a Wizard</h1>

{% endblock %}

main_app/templates/main_app/spell_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Spell</h1>

<h4>Are you sure you want to delete this spell
    <span class="teal-text">{{object.name}}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete" />
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/spell_form.html
{% extends 'base.html' %} {% block content %}

{% if object %}
<h1>Update {{object.name}}</h1>
{% else %}
<h1>Add Spell</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Spell {% else %} Add Spell {% endif %}" />
</form>

{% endblock %}

main_app/templates/main_app/wizard_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1> Obliviate</h1>

<h4>
    Are you sure you want to erase the memory of this wizard
    <span class="teal-text">{{ objects.name }} </span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Obliviate" class="btn" />
    <a href="{% url 'detail' wizard.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/wizard_form.html
{% extends 'base.html' %} {% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Wizard </h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" />
</form>

{% endblock %}

main_app/templates/spells/detail.html
{% extends 'base.html' %} {% block content%}

<h1>Spell Details</h1>

<div class="card">
    <a href="{% url 'spells_detail' spell.id %}">
        <div class="card-content">
            <span class="card-title">
            <span>Spell Name:  {{ spell.name }}</span> 
                  Spell Action:  {{ spell.action }}
            </span>
        </div>
        <div class="card-action">
            <a href="{% url 'spells_update' spell.id %}">Edit</a>
            <a href="{% url 'spells_delete' spell.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/spells/index.html
{% extends 'base.html' %} {% block content %}

<h1>Spells List</h1>

{% for spell in object_list %}
<div class="card">
    <a href="{% url 'spells_detail' spell.id %}">
        <div class="card-content">
            <span class="card-title">{{spell.name}}
            </span> {{spell.action}}   
        </div>
    </a>
</div>

{% endfor %} {% endblock %}

main_app/templates/wizards/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Wizard Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ wizard.name }}</span>
        <!-- <p>Owner: {{ wand.owner }}</p> -->
        <p>Age: {{ wizard.age }}</p>
        <p>House: {{ wizard.house }}</p>
        <p>Profession: {{ wizard.profession }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'wizards_update' wizard.id %}"> Edit</a>
        <a href="{% url 'wizards_delete' wizard.id %}"> Delete</a>
      </div>
    </div>
    {% for photo in wizard.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}" alt="{{wizard.name}}">
    {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}   
    <form 
        action="{% url 'add_photo' wizard.id %}"
        enctype="multipart/form-data"
        method="POST"
        class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file" />
        <br /><br />
        <input type="submit" class="btn" value="Upload Photo" />
    </form>
</div>
<div class="col s6">
    <form action="{% url 'add_wand' wizard.id %}" method="post">
        {% csrf_token %} {{ wand_form.as_p }}
        <input type="submit" class="btn" value="Add Wand" />
    </form>
      <table class="striped">
        <thead>
          <tr>
            <th>Length</th>
            <th>Core</th>
            <th>Wood</th>
          </tr>
        </thead>
        <tbody>
          {% for wand in wizard.wand_set.all %}
          <tr>
            <td>{{wand.length}}</td>
            <td>{{wand.core}}</td>
            <td>{{wand.wood}}</td>
            <td>{{wand.get_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <hr />
  <div class="row">
    <div class="col s6">
      <h3>{{wizard.name}}'s Spells</h3>
      {% if wizard.spells.count %} {% for spell in wizard.spells.all %}
      <div class="card">
        <div class="card-content">
          <div class="card-title">
            <span> {{spell.name}}</span>
            {{spell.action}}
          </div>
        </div>
      
      <div class="card-action">
        <form
          action="{% url 'assoc_spell_delete' wizard.id spell.id %}"
          method="POST">
        {% csrf_token %}
            <button type="submit" class="btn red">Remove</button>
        </form>
      </div>
    </div> 
      {% endfor %} {% else %}
      <h5>No Spells</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Spells</h3>
      {% if spells.count %} {% for spell in spells.all %}
      <div class="card">
        <div class="card-content">
          <div class="card-title">
            <span>{{ spell.name }}</span>
            {{ spell.action }}
          </div>
        </div>
  
        <div class="card-action">
          <form action="{% url 'assoc_spell' wizard.id spell.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">ADD</button>
          </form>
        </div>
      </div>
      {% endfor %} 
    {% else %}
      <h5>{{ wizard.name }} Already Has All Spells Available</h5>
      {% endif %}
    </div>
  </div>
  {% endblock %}

main_app/templates/wizards/index.html
{% extends 'base.html' %} {% block content %}

<h1>Registered Wizards</h1>

{% for wizard in wizards %}

<div class="card">
    <a href="{% url 'detail' wizard.id %}">

        <div class="card-content">
            <span class="card-title">{{ wizard.name }}</span>
            <!-- <p>Owner: {{ wand.owner }}</p> -->
            <p>Age: {{ wizard.age }}</p>
            <p>House: {{ wizard.house }}</p>
            <p>Profession: {{ wizard.profession }}</p>
            
        </div>
    </a>
</div>
{% endfor %} {% endblock %}